# Generated by Django 4.0.6 on 2022-09-13 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('league_points', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fixture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('odds_team_home', models.DecimalField(decimal_places=2, max_digits=3)),
                ('odds_draw', models.DecimalField(decimal_places=2, max_digits=3)),
                ('odds_team_away', models.DecimalField(decimal_places=2, max_digits=3)),
                ('match_num', models.IntegerField(blank=True, default=0, null=True)),
                ('date', models.DateTimeField()),
                ('team_away', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='away_team', to='royalbetsapp.team')),
                ('team_home', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='home_team', to='royalbetsapp.team')),
            ],
        ),
    ]
