# Generated by Django 4.0.6 on 2022-09-13 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('royalbetsapp', '0002_team_draws_team_form_team_goals_conceded_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='form',
            field=models.CharField(blank=True, default='', max_length=5),
        ),
    ]
