# Generated by Django 4.0.6 on 2022-09-14 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('royalbetsapp', '0004_remove_team_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixture',
            name='week',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
