# Generated by Django 4.0.6 on 2022-09-16 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('royalbetsapp', '0005_fixture_week'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixture',
            name='odds_draw',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='fixture',
            name='odds_team_away',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='fixture',
            name='odds_team_home',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='team',
            name='form',
            field=models.CharField(blank=True, default='?????', max_length=5),
        ),
    ]
