# Generated by Django 4.0.6 on 2022-09-16 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('royalbetsapp', '0006_alter_fixture_odds_draw_alter_fixture_odds_team_away_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='form',
            field=models.CharField(blank=True, default='00000', max_length=5),
        ),
    ]
